-- ============================================================
-- Migration 008: vehicle_catalog seed — batch 1 (284 variants)
-- Researcher-verified data: Maruti Suzuki, Hyundai, Tata, Honda,
-- Kia, Toyota, MG, Mahindra, Volkswagen, Skoda, Jeep, Renault
-- (and more). Progressive batches continue as 009, 010, ...
--
-- ON CONFLICT DO NOTHING: safe to re-run or apply on top of 007.
-- make + model in Title Case — rc_extractor normalizes OCR output
-- to .title() before lookup.
-- ============================================================

insert into public.vehicle_catalog
  (make, model, variant, year_start, year_end,
   body_type, fuel_type, transmission, features, colors)
values
  ('Maruti Suzuki', 'Swift', 'LXi MT', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor","USB Charger"}', '{"Pearl Arctic White","Magma Grey","Splendid Silver","Sizzling Red","Luster Blue"}'),
  ('Maruti Suzuki', 'Swift', 'VXi MT', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor","USB Charger"}', '{"Pearl Arctic White","Magma Grey","Splendid Silver","Sizzling Red","Luster Blue"}'),
  ('Maruti Suzuki', 'Swift', 'VXi AMT', 2024, 2026, 'hatchback', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Sensor","USB Charger"}', '{"Pearl Arctic White","Magma Grey","Splendid Silver","Sizzling Red","Luster Blue"}'),
  ('Maruti Suzuki', 'Swift', 'VXi CNG', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor","USB Charger"}', '{"Pearl Arctic White","Magma Grey","Splendid Silver","Sizzling Red","Luster Blue"}'),
  ('Maruti Suzuki', 'Swift', 'ZXi MT', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor","USB Charger"}', '{"Pearl Arctic White","Magma Grey","Splendid Silver","Sizzling Red","Luster Blue"}'),
  ('Maruti Suzuki', 'Swift', 'ZXi AMT', 2024, 2026, 'hatchback', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Sensor","USB Charger"}', '{"Pearl Arctic White","Magma Grey","Splendid Silver","Sizzling Red","Luster Blue"}'),
  ('Maruti Suzuki', 'Swift', 'ZXi+ MT', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor","USB Charger"}', '{"Pearl Arctic White","Magma Grey","Splendid Silver","Sizzling Red","Luster Blue"}'),
  ('Maruti Suzuki', 'Swift', 'ZXi+ AMT', 2024, 2026, 'hatchback', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Sensor","USB Charger"}', '{"Pearl Arctic White","Magma Grey","Splendid Silver","Sizzling Red","Luster Blue"}'),
  ('Maruti Suzuki', 'Alto K10', 'LXi MT', 2022, 2026, 'hatchback', 'petrol', 'manual', '{"Rear Parking Sensor"}', '{}'),
  ('Maruti Suzuki', 'Alto K10', 'VXi MT', 2022, 2026, 'hatchback', 'petrol', 'manual', '{"Rear Parking Sensor"}', '{}'),
  ('Maruti Suzuki', 'Alto K10', 'VXi AMT', 2022, 2026, 'hatchback', 'petrol', 'automatic', '{"Rear Parking Sensor"}', '{}'),
  ('Maruti Suzuki', 'Alto K10', 'ZXi MT', 2022, 2026, 'hatchback', 'petrol', 'manual', '{"Rear Parking Sensor"}', '{}'),
  ('Maruti Suzuki', 'Alto K10', 'ZXi AMT', 2022, 2026, 'hatchback', 'petrol', 'automatic', '{"Rear Parking Sensor"}', '{}'),
  ('Maruti Suzuki', 'WagonR', 'LXi MT', 2022, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{"Poolside Blue","Nutmeg Brown","Silky Silver","Magma Grey","Superior White"}'),
  ('Maruti Suzuki', 'WagonR', 'VXi MT', 2022, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{"Poolside Blue","Nutmeg Brown","Silky Silver","Magma Grey","Superior White"}'),
  ('Maruti Suzuki', 'WagonR', 'VXi AMT', 2022, 2026, 'hatchback', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{"Poolside Blue","Nutmeg Brown","Silky Silver","Magma Grey","Superior White"}'),
  ('Maruti Suzuki', 'WagonR', 'ZXi MT', 2022, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{"Poolside Blue","Nutmeg Brown","Silky Silver","Magma Grey","Superior White"}'),
  ('Maruti Suzuki', 'WagonR', 'ZXi AMT', 2022, 2026, 'hatchback', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{"Poolside Blue","Nutmeg Brown","Silky Silver","Magma Grey","Superior White"}'),
  ('Maruti Suzuki', 'WagonR', 'ZXi+ MT', 2022, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{"Poolside Blue","Nutmeg Brown","Silky Silver","Magma Grey","Superior White"}'),
  ('Maruti Suzuki', 'WagonR', 'ZXi+ AMT', 2022, 2026, 'hatchback', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{"Poolside Blue","Nutmeg Brown","Silky Silver","Magma Grey","Superior White"}'),
  ('Maruti Suzuki', 'Brezza', 'LXi MT', 2022, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Exuberant Blue","Magma Grey","Brave Khakhi","Splendid Silver","Pearl Arctic White"}'),
  ('Maruti Suzuki', 'Brezza', 'VXi MT', 2022, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Exuberant Blue","Magma Grey","Brave Khakhi","Splendid Silver","Pearl Arctic White"}'),
  ('Maruti Suzuki', 'Brezza', 'ZXi MT', 2022, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Exuberant Blue","Magma Grey","Brave Khakhi","Splendid Silver","Pearl Arctic White"}'),
  ('Maruti Suzuki', 'Brezza', 'ZXi AT', 2022, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Exuberant Blue","Magma Grey","Brave Khakhi","Splendid Silver","Pearl Arctic White"}'),
  ('Maruti Suzuki', 'Brezza', 'ZXi+ MT', 2022, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Exuberant Blue","Magma Grey","Brave Khakhi","Splendid Silver","Pearl Arctic White"}'),
  ('Maruti Suzuki', 'Brezza', 'ZXi+ AT', 2022, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Exuberant Blue","Magma Grey","Brave Khakhi","Splendid Silver","Pearl Arctic White"}'),
  ('Maruti Suzuki', 'Grand Vitara', 'Sigma MT', 2022, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Nexa Blue","Arctic White","Grandeur Grey","Chestnut Brown"}'),
  ('Maruti Suzuki', 'Grand Vitara', 'Delta MT', 2022, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Nexa Blue","Arctic White","Grandeur Grey","Chestnut Brown"}'),
  ('Maruti Suzuki', 'Grand Vitara', 'Delta AT', 2022, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Nexa Blue","Arctic White","Grandeur Grey","Chestnut Brown"}'),
  ('Maruti Suzuki', 'Grand Vitara', 'Zeta MT', 2022, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Nexa Blue","Arctic White","Grandeur Grey","Chestnut Brown"}'),
  ('Maruti Suzuki', 'Grand Vitara', 'Zeta AT', 2022, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Nexa Blue","Arctic White","Grandeur Grey","Chestnut Brown"}'),
  ('Maruti Suzuki', 'Grand Vitara', 'Alpha MT', 2022, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Nexa Blue","Arctic White","Grandeur Grey","Chestnut Brown"}'),
  ('Maruti Suzuki', 'Grand Vitara', 'Alpha AT', 2022, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Nexa Blue","Arctic White","Grandeur Grey","Chestnut Brown"}'),
  ('Maruti Suzuki', 'Fronx', 'Sigma MT', 2023, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Nexa Blue","Arctic White","Splendid Silver","Earthy Brown"}'),
  ('Maruti Suzuki', 'Fronx', 'Delta MT', 2023, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Nexa Blue","Arctic White","Splendid Silver","Earthy Brown"}'),
  ('Maruti Suzuki', 'Fronx', 'Delta+ AT', 2023, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Nexa Blue","Arctic White","Splendid Silver","Earthy Brown"}'),
  ('Maruti Suzuki', 'Fronx', 'Zeta MT', 2023, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Nexa Blue","Arctic White","Splendid Silver","Earthy Brown"}'),
  ('Maruti Suzuki', 'Fronx', 'Zeta AT', 2023, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Nexa Blue","Arctic White","Splendid Silver","Earthy Brown"}'),
  ('Maruti Suzuki', 'Fronx', 'Alpha MT', 2023, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Nexa Blue","Arctic White","Splendid Silver","Earthy Brown"}'),
  ('Maruti Suzuki', 'Fronx', 'Alpha AT', 2023, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Nexa Blue","Arctic White","Splendid Silver","Earthy Brown"}'),
  ('Maruti Suzuki', 'Ertiga', 'LXi MT', 2022, 2026, 'muv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear AC Vents","Rear Parking Sensor"}', '{}'),
  ('Maruti Suzuki', 'Ertiga', 'VXi MT', 2022, 2026, 'muv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear AC Vents","Rear Parking Sensor"}', '{}'),
  ('Maruti Suzuki', 'Ertiga', 'VXi CNG MT', 2022, 2026, 'muv', 'cng', 'manual', '{"Apple CarPlay","Android Auto","Rear AC Vents","Rear Parking Sensor"}', '{}'),
  ('Maruti Suzuki', 'Ertiga', 'ZXi MT', 2022, 2026, 'muv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear AC Vents","Rear Parking Sensor"}', '{}'),
  ('Maruti Suzuki', 'Ertiga', 'ZXi+ AT', 2022, 2026, 'muv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear AC Vents","Rear Parking Sensor"}', '{}'),
  ('Hyundai', 'i20', 'Era', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{"Amazon Grey","Atlas White","Fiery Red","Starry Night","Titan Grey","Abyss Black - Knight"}'),
  ('Hyundai', 'i20', 'Magna Executive', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{"Amazon Grey","Atlas White","Fiery Red","Starry Night","Titan Grey","Abyss Black - Knight"}'),
  ('Hyundai', 'i20', 'Magna', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{"Amazon Grey","Atlas White","Fiery Red","Starry Night","Titan Grey","Abyss Black - Knight"}'),
  ('Hyundai', 'i20', 'Sportz', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{"Amazon Grey","Atlas White","Fiery Red","Starry Night","Titan Grey","Abyss Black - Knight"}'),
  ('Hyundai', 'i20', 'Sportz(O)', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{"Amazon Grey","Atlas White","Fiery Red","Starry Night","Titan Grey","Abyss Black - Knight"}'),
  ('Hyundai', 'i20', 'Sportz(O) Knight', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{"Amazon Grey","Atlas White","Fiery Red","Starry Night","Titan Grey","Abyss Black - Knight"}'),
  ('Hyundai', 'i20', 'Asta', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{"Amazon Grey","Atlas White","Fiery Red","Starry Night","Titan Grey","Abyss Black - Knight"}'),
  ('Hyundai', 'i20', 'Asta (O)', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{"Amazon Grey","Atlas White","Fiery Red","Starry Night","Titan Grey","Abyss Black - Knight"}'),
  ('Hyundai', 'i20', 'Asta(O) Knight', 2024, 2026, 'hatchback', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{"Amazon Grey","Atlas White","Fiery Red","Starry Night","Titan Grey","Abyss Black - Knight"}'),
  ('Hyundai', 'Creta', 'E', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{"Abyss Black","Atlas White","Titan Grey","Robust Emerald Pearl","Fiery Red"}'),
  ('Hyundai', 'Creta', 'EX', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{"Abyss Black","Atlas White","Titan Grey","Robust Emerald Pearl","Fiery Red"}'),
  ('Hyundai', 'Creta', 'EX(O)', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{"Abyss Black","Atlas White","Titan Grey","Robust Emerald Pearl","Fiery Red"}'),
  ('Hyundai', 'Creta', 'S(O)', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{"Abyss Black","Atlas White","Titan Grey","Robust Emerald Pearl","Fiery Red"}'),
  ('Hyundai', 'Creta', 'SX', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{"Abyss Black","Atlas White","Titan Grey","Robust Emerald Pearl","Fiery Red"}'),
  ('Hyundai', 'Creta', 'SX Premium', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{"Abyss Black","Atlas White","Titan Grey","Robust Emerald Pearl","Fiery Red"}'),
  ('Hyundai', 'Creta', 'King', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{"Abyss Black","Atlas White","Titan Grey","Robust Emerald Pearl","Fiery Red"}'),
  ('Hyundai', 'Creta', 'King Knight', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{"Abyss Black","Atlas White","Titan Grey","Robust Emerald Pearl","Fiery Red"}'),
  ('Hyundai', 'Verna', 'EX', 2023, 2026, 'sedan', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Wireless Charger","Cruise Control"}', '{"Titan Grey","Abyss Black Pearl","Atlas White","Fiery Red","Tellurian Brown"}'),
  ('Hyundai', 'Verna', 'S', 2023, 2026, 'sedan', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Wireless Charger","Cruise Control"}', '{"Titan Grey","Abyss Black Pearl","Atlas White","Fiery Red","Tellurian Brown"}'),
  ('Hyundai', 'Verna', 'SX', 2023, 2026, 'sedan', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Wireless Charger","Cruise Control"}', '{"Titan Grey","Abyss Black Pearl","Atlas White","Fiery Red","Tellurian Brown"}'),
  ('Hyundai', 'Verna', 'SX(O)', 2023, 2026, 'sedan', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Wireless Charger","Cruise Control"}', '{"Titan Grey","Abyss Black Pearl","Atlas White","Fiery Red","Tellurian Brown"}'),
  ('Hyundai', 'Aura', 'E', 2023, 2026, 'sedan', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Rear AC Vents"}', '{"Titan Grey","Typhoon Silver","Polar White","Starry Night","Fiery Red"}'),
  ('Hyundai', 'Aura', 'S', 2023, 2026, 'sedan', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Rear AC Vents"}', '{"Titan Grey","Typhoon Silver","Polar White","Starry Night","Fiery Red"}'),
  ('Hyundai', 'Aura', 'SX', 2023, 2026, 'sedan', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Rear AC Vents"}', '{"Titan Grey","Typhoon Silver","Polar White","Starry Night","Fiery Red"}'),
  ('Hyundai', 'Aura', 'SX(O)', 2023, 2026, 'sedan', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Rear AC Vents"}', '{"Titan Grey","Typhoon Silver","Polar White","Starry Night","Fiery Red"}'),
  ('Hyundai', 'Aura', 'SX+', 2023, 2026, 'sedan', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Rear AC Vents"}', '{"Titan Grey","Typhoon Silver","Polar White","Starry Night","Fiery Red"}'),
  ('Hyundai', 'Exter', 'EX', 2023, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Ranger Khaki","Cosmic Gold","Titan Grey","Starry Night","Atlas White"}'),
  ('Hyundai', 'Exter', 'S', 2023, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Ranger Khaki","Cosmic Gold","Titan Grey","Starry Night","Atlas White"}'),
  ('Hyundai', 'Exter', 'S Smart', 2023, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Ranger Khaki","Cosmic Gold","Titan Grey","Starry Night","Atlas White"}'),
  ('Hyundai', 'Exter', 'SX', 2023, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Ranger Khaki","Cosmic Gold","Titan Grey","Starry Night","Atlas White"}'),
  ('Hyundai', 'Exter', 'SX Smart', 2023, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Ranger Khaki","Cosmic Gold","Titan Grey","Starry Night","Atlas White"}'),
  ('Hyundai', 'Exter', 'SX(O)', 2023, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Ranger Khaki","Cosmic Gold","Titan Grey","Starry Night","Atlas White"}'),
  ('Hyundai', 'Exter', 'SX(O) Connect', 2023, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Ranger Khaki","Cosmic Gold","Titan Grey","Starry Night","Atlas White"}'),
  ('Hyundai', 'Exter', 'SX Knight', 2023, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Ranger Khaki","Cosmic Gold","Titan Grey","Starry Night","Atlas White"}'),
  ('Hyundai', 'Venue', 'HX 2', 2025, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Hyundai', 'Venue', 'HX 4', 2025, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Hyundai', 'Venue', 'HX 5', 2025, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Hyundai', 'Venue', 'HX 5+', 2025, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Hyundai', 'Venue', 'HX 6', 2025, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Hyundai', 'Venue', 'HX 7', 2025, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Hyundai', 'Venue', 'HX 8', 2025, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Hyundai', 'Venue', 'HX 10', 2025, 2026, 'suv', 'diesel', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Hyundai', 'Venue', 'HX 5 Knight', 2025, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Hyundai', 'Venue', 'HX 8 Knight', 2025, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Hyundai', 'Venue', 'HX 10 Knight', 2025, 2026, 'suv', 'diesel', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Tata', 'Nexon', 'Smart', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Pristine White","Daytona Grey","Fearless Purple","Creative Ocean","Flame Red"}'),
  ('Tata', 'Nexon', 'Pure', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Pristine White","Daytona Grey","Fearless Purple","Creative Ocean","Flame Red"}'),
  ('Tata', 'Nexon', 'Pure S', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Pristine White","Daytona Grey","Fearless Purple","Creative Ocean","Flame Red"}'),
  ('Tata', 'Nexon', 'Creative', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Pristine White","Daytona Grey","Fearless Purple","Creative Ocean","Flame Red"}'),
  ('Tata', 'Nexon', 'Creative+', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Pristine White","Daytona Grey","Fearless Purple","Creative Ocean","Flame Red"}'),
  ('Tata', 'Nexon', 'Fearless', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Pristine White","Daytona Grey","Fearless Purple","Creative Ocean","Flame Red"}'),
  ('Tata', 'Nexon', 'Fearless+', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Pristine White","Daytona Grey","Fearless Purple","Creative Ocean","Flame Red"}'),
  ('Tata', 'Nexon', 'Smart+ CNG', 2024, 2026, 'suv', 'cng', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Pristine White","Daytona Grey","Fearless Purple","Creative Ocean","Flame Red"}'),
  ('Tata', 'Nexon', 'Pure+ CNG', 2024, 2026, 'suv', 'cng', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Pristine White","Daytona Grey","Fearless Purple","Creative Ocean","Flame Red"}'),
  ('Tata', 'Nexon', 'Creative+ CNG', 2024, 2026, 'suv', 'cng', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Pristine White","Daytona Grey","Fearless Purple","Creative Ocean","Flame Red"}'),
  ('Tata', 'Punch', 'Smart', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Tropical Mist","Atomic Orange","Calypso Red","Meteor Bronze","Pearl White"}'),
  ('Tata', 'Punch', 'Pure', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Tropical Mist","Atomic Orange","Calypso Red","Meteor Bronze","Pearl White"}'),
  ('Tata', 'Punch', 'Adventure', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Tropical Mist","Atomic Orange","Calypso Red","Meteor Bronze","Pearl White"}'),
  ('Tata', 'Punch', 'Adventure S', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Tropical Mist","Atomic Orange","Calypso Red","Meteor Bronze","Pearl White"}'),
  ('Tata', 'Punch', 'Accomplished', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Tropical Mist","Atomic Orange","Calypso Red","Meteor Bronze","Pearl White"}'),
  ('Tata', 'Punch', 'Accomplished+', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Tropical Mist","Atomic Orange","Calypso Red","Meteor Bronze","Pearl White"}'),
  ('Tata', 'Punch', 'Creative', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Tropical Mist","Atomic Orange","Calypso Red","Meteor Bronze","Pearl White"}'),
  ('Tata', 'Altroz', 'XE', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{"Harbour Blue","High Street Gold","Downtown Red","Arcade Grey","Pure Silver"}'),
  ('Tata', 'Altroz', 'XM', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{"Harbour Blue","High Street Gold","Downtown Red","Arcade Grey","Pure Silver"}'),
  ('Tata', 'Altroz', 'XT', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{"Harbour Blue","High Street Gold","Downtown Red","Arcade Grey","Pure Silver"}'),
  ('Tata', 'Altroz', 'XZ', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{"Harbour Blue","High Street Gold","Downtown Red","Arcade Grey","Pure Silver"}'),
  ('Tata', 'Altroz', 'XZ+', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{"Harbour Blue","High Street Gold","Downtown Red","Arcade Grey","Pure Silver"}'),
  ('Tata', 'Tiago', 'XE', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Flame Red","Pearlescent White","Daytona Grey","Midnight Plum"}'),
  ('Tata', 'Tiago', 'XM', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Flame Red","Pearlescent White","Daytona Grey","Midnight Plum"}'),
  ('Tata', 'Tiago', 'XT', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Flame Red","Pearlescent White","Daytona Grey","Midnight Plum"}'),
  ('Tata', 'Tiago', 'XZ+', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Flame Red","Pearlescent White","Daytona Grey","Midnight Plum"}'),
  ('Tata', 'Tiago', 'XZA+', 2024, 2026, 'hatchback', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Flame Red","Pearlescent White","Daytona Grey","Midnight Plum"}'),
  ('Tata', 'Tiago', 'XM+ CNG', 2024, 2026, 'hatchback', 'cng', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Flame Red","Pearlescent White","Daytona Grey","Midnight Plum"}'),
  ('Tata', 'Tiago', 'XT CNG', 2024, 2026, 'hatchback', 'cng', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Flame Red","Pearlescent White","Daytona Grey","Midnight Plum"}'),
  ('Tata', 'Tiago', 'XZ+ CNG', 2024, 2026, 'hatchback', 'cng', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Flame Red","Pearlescent White","Daytona Grey","Midnight Plum"}'),
  ('Tata', 'Harrier', 'Smart', 2024, 2026, 'suv', 'diesel', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","Cruise Control","Rear AC Vents"}', '{}'),
  ('Tata', 'Harrier', 'Pure', 2024, 2026, 'suv', 'diesel', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","Cruise Control","Rear AC Vents"}', '{}'),
  ('Tata', 'Harrier', 'Adventure', 2024, 2026, 'suv', 'diesel', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","Cruise Control","Rear AC Vents"}', '{}'),
  ('Tata', 'Harrier', 'Fearless', 2024, 2026, 'suv', 'diesel', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","Cruise Control","Rear AC Vents"}', '{}'),
  ('Tata', 'Harrier', 'Fearless+', 2024, 2026, 'suv', 'diesel', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","Cruise Control","Rear AC Vents"}', '{}'),
  ('Tata', 'Safari', 'Smart', 2024, 2026, 'suv', 'diesel', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","Cruise Control","Rear AC Vents","Captain Seats"}', '{}'),
  ('Tata', 'Safari', 'Pure', 2024, 2026, 'suv', 'diesel', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","Cruise Control","Rear AC Vents","Captain Seats"}', '{}'),
  ('Tata', 'Safari', 'Adventure', 2024, 2026, 'suv', 'diesel', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","Cruise Control","Rear AC Vents","Captain Seats"}', '{}'),
  ('Tata', 'Safari', 'Fearless', 2024, 2026, 'suv', 'diesel', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","Cruise Control","Rear AC Vents","Captain Seats"}', '{}'),
  ('Tata', 'Safari', 'Fearless+', 2024, 2026, 'suv', 'diesel', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","Cruise Control","Rear AC Vents","Captain Seats"}', '{}'),
  ('Tata', 'Nexon EV', 'Smart', 2024, 2026, 'suv', 'electric', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","Cruise Control","Wireless Charger"}', '{}'),
  ('Tata', 'Nexon EV', 'Pure+', 2024, 2026, 'suv', 'electric', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","Cruise Control","Wireless Charger"}', '{}'),
  ('Tata', 'Nexon EV', 'Fearless', 2024, 2026, 'suv', 'electric', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","Cruise Control","Wireless Charger"}', '{}'),
  ('Tata', 'Nexon EV', 'Empowered', 2024, 2026, 'suv', 'electric', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","Cruise Control","Wireless Charger"}', '{}'),
  ('Mahindra', 'Scorpio-N', 'Z2', 2023, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{}'),
  ('Mahindra', 'Scorpio-N', 'Z4', 2023, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{}'),
  ('Mahindra', 'Scorpio-N', 'Z8', 2023, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{}'),
  ('Mahindra', 'Scorpio-N', 'Z8 L', 2023, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{}'),
  ('Mahindra', 'Scorpio-N', 'Z6', 2023, 2026, 'suv', 'diesel', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{}'),
  ('Mahindra', 'Scorpio-N', 'Z8 L 4WD', 2023, 2026, 'suv', 'diesel', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{}'),
  ('Mahindra', 'XUV 3XO', 'MX1', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{}'),
  ('Mahindra', 'XUV 3XO', 'MX2 Pro', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{}'),
  ('Mahindra', 'XUV 3XO', 'MX3', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{}'),
  ('Mahindra', 'XUV 3XO', 'AX5', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{}'),
  ('Mahindra', 'XUV 3XO', 'AX7 L', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{}'),
  ('Mahindra', 'Thar Roxx', 'MX1', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{}'),
  ('Mahindra', 'Thar Roxx', 'MX3', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{}'),
  ('Mahindra', 'Thar Roxx', 'AX5', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{}'),
  ('Mahindra', 'Thar Roxx', 'AX7', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{}'),
  ('Mahindra', 'Thar Roxx', 'AX7 L', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{}'),
  ('Mahindra', 'Thar Roxx', 'AX7 L 4WD', 2024, 2026, 'suv', 'diesel', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{}'),
  ('Mahindra', 'XUV700', 'MX', 2021, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","ADAS","Wireless Charger"}', '{}'),
  ('Mahindra', 'XUV700', 'AX3', 2021, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","ADAS","Wireless Charger"}', '{}'),
  ('Mahindra', 'XUV700', 'AX5', 2021, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","ADAS","Wireless Charger"}', '{}'),
  ('Mahindra', 'XUV700', 'AX7', 2021, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","ADAS","Wireless Charger"}', '{}'),
  ('Mahindra', 'XUV700', 'AX7 L', 2021, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","ADAS","Wireless Charger"}', '{}'),
  ('Toyota', 'Glanza', 'E', 2022, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Cafe White","Insta Blue","Gaming Grey","Sportin Red","Enticing Silver"}'),
  ('Toyota', 'Glanza', 'S', 2022, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Cafe White","Insta Blue","Gaming Grey","Sportin Red","Enticing Silver"}'),
  ('Toyota', 'Glanza', 'G', 2022, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Cafe White","Insta Blue","Gaming Grey","Sportin Red","Enticing Silver"}'),
  ('Toyota', 'Urban Cruiser Hyryder', 'E', 2022, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Cafe White","Midnight Black","Speedy Blue","Gaming Grey","Enticing Silver"}'),
  ('Toyota', 'Urban Cruiser Hyryder', 'S', 2022, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Cafe White","Midnight Black","Speedy Blue","Gaming Grey","Enticing Silver"}'),
  ('Toyota', 'Urban Cruiser Hyryder', 'G', 2022, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Cafe White","Midnight Black","Speedy Blue","Gaming Grey","Enticing Silver"}'),
  ('Toyota', 'Urban Cruiser Hyryder', 'V', 2022, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{"Cafe White","Midnight Black","Speedy Blue","Gaming Grey","Enticing Silver"}'),
  ('Toyota', 'Innova Hycross', 'GX', 2023, 2026, 'muv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear AC Vents","Captain Seats"}', '{}'),
  ('Toyota', 'Innova Hycross', 'VX', 2023, 2026, 'muv', 'hybrid', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear AC Vents","Captain Seats"}', '{}'),
  ('Toyota', 'Innova Hycross', 'ZX', 2023, 2026, 'muv', 'hybrid', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear AC Vents","Captain Seats"}', '{}'),
  ('Toyota', 'Fortuner', '4x2 MT', 2021, 2026, 'suv', 'diesel', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Toyota', 'Fortuner', '4x2 AT', 2021, 2026, 'suv', 'diesel', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Toyota', 'Fortuner', '4x4 MT', 2021, 2026, 'suv', 'diesel', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Toyota', 'Fortuner', '4x4 AT', 2021, 2026, 'suv', 'diesel', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Toyota', 'Innova Crysta', 'GX MT', 2021, 2026, 'muv', 'diesel', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear AC Vents"}', '{}'),
  ('Toyota', 'Innova Crysta', 'GX AT', 2021, 2026, 'muv', 'diesel', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear AC Vents"}', '{}'),
  ('Toyota', 'Innova Crysta', 'VX 7 STR', 2021, 2026, 'muv', 'diesel', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear AC Vents"}', '{}'),
  ('Toyota', 'Innova Crysta', 'VX 8 STR', 2021, 2026, 'muv', 'diesel', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear AC Vents"}', '{}'),
  ('Kia', 'Seltos', 'HTE', 2023, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","360 Camera","ADAS","Cruise Control"}', '{"Frost Blue","Morning Haze","Magma Red","Ivory Silver Gloss","Pewter Olive","Imperial Blue","Gravity Gray","Aurora Black Pearl","Glacier White Pearl"}'),
  ('Kia', 'Seltos', 'HTE(O)', 2023, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","360 Camera","ADAS","Cruise Control"}', '{"Frost Blue","Morning Haze","Magma Red","Ivory Silver Gloss","Pewter Olive","Imperial Blue","Gravity Gray","Aurora Black Pearl","Glacier White Pearl"}'),
  ('Kia', 'Seltos', 'HTK', 2023, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","360 Camera","ADAS","Cruise Control"}', '{"Frost Blue","Morning Haze","Magma Red","Ivory Silver Gloss","Pewter Olive","Imperial Blue","Gravity Gray","Aurora Black Pearl","Glacier White Pearl"}'),
  ('Kia', 'Seltos', 'HTK(O)', 2023, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","360 Camera","ADAS","Cruise Control"}', '{"Frost Blue","Morning Haze","Magma Red","Ivory Silver Gloss","Pewter Olive","Imperial Blue","Gravity Gray","Aurora Black Pearl","Glacier White Pearl"}'),
  ('Kia', 'Seltos', 'HTX', 2023, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","360 Camera","ADAS","Cruise Control"}', '{"Frost Blue","Morning Haze","Magma Red","Ivory Silver Gloss","Pewter Olive","Imperial Blue","Gravity Gray","Aurora Black Pearl","Glacier White Pearl"}'),
  ('Kia', 'Seltos', 'HTX(A)', 2023, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","360 Camera","ADAS","Cruise Control"}', '{"Frost Blue","Morning Haze","Magma Red","Ivory Silver Gloss","Pewter Olive","Imperial Blue","Gravity Gray","Aurora Black Pearl","Glacier White Pearl"}'),
  ('Kia', 'Seltos', 'GTX', 2023, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","360 Camera","ADAS","Cruise Control"}', '{"Frost Blue","Morning Haze","Magma Red","Ivory Silver Gloss","Pewter Olive","Imperial Blue","Gravity Gray","Aurora Black Pearl","Glacier White Pearl"}'),
  ('Kia', 'Seltos', 'GTX(A)', 2023, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","360 Camera","ADAS","Cruise Control"}', '{"Frost Blue","Morning Haze","Magma Red","Ivory Silver Gloss","Pewter Olive","Imperial Blue","Gravity Gray","Aurora Black Pearl","Glacier White Pearl"}'),
  ('Kia', 'Seltos', 'X-Line', 2023, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","360 Camera","ADAS","Cruise Control"}', '{"Frost Blue","Morning Haze","Magma Red","Ivory Silver Gloss","Pewter Olive","Imperial Blue","Gravity Gray","Aurora Black Pearl","Glacier White Pearl"}'),
  ('Kia', 'Seltos', 'GTX(O)', 2023, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","360 Camera","ADAS","Cruise Control"}', '{"Frost Blue","Morning Haze","Magma Red","Ivory Silver Gloss","Pewter Olive","Imperial Blue","Gravity Gray","Aurora Black Pearl","Glacier White Pearl"}'),
  ('Kia', 'Seltos', 'X-Line(O)', 2023, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","360 Camera","ADAS","Cruise Control"}', '{"Frost Blue","Morning Haze","Magma Red","Ivory Silver Gloss","Pewter Olive","Imperial Blue","Gravity Gray","Aurora Black Pearl","Glacier White Pearl"}'),
  ('Kia', 'Sonet', 'HTE', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Kia', 'Sonet', 'HTK', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Kia', 'Sonet', 'HTX', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Kia', 'Sonet', 'HTX+', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Kia', 'Sonet', 'GTX+', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Kia', 'Carens', 'Premium', 2024, 2026, 'muv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear AC Vents","Captain Seats"}', '{}'),
  ('Kia', 'Carens', 'Prestige', 2024, 2026, 'muv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear AC Vents","Captain Seats"}', '{}'),
  ('Kia', 'Carens', 'Prestige Plus', 2024, 2026, 'muv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear AC Vents","Captain Seats"}', '{}'),
  ('Kia', 'Carens', 'Luxury', 2024, 2026, 'muv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear AC Vents","Captain Seats"}', '{}'),
  ('Honda', 'City', 'SV', 2023, 2026, 'sedan', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{"Radiant Red Metallic","Golden Brown Metallic","Platinum White Pearl","Meteoroid Grey Metallic","Obsidian Blue Pearl"}'),
  ('Honda', 'City', 'V', 2023, 2026, 'sedan', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{"Radiant Red Metallic","Golden Brown Metallic","Platinum White Pearl","Meteoroid Grey Metallic","Obsidian Blue Pearl"}'),
  ('Honda', 'City', 'VX', 2023, 2026, 'sedan', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{"Radiant Red Metallic","Golden Brown Metallic","Platinum White Pearl","Meteoroid Grey Metallic","Obsidian Blue Pearl"}'),
  ('Honda', 'City', 'ZX', 2023, 2026, 'sedan', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{"Radiant Red Metallic","Golden Brown Metallic","Platinum White Pearl","Meteoroid Grey Metallic","Obsidian Blue Pearl"}'),
  ('Honda', 'Amaze', 'E', 2024, 2026, 'sedan', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Honda', 'Amaze', 'S', 2024, 2026, 'sedan', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Honda', 'Amaze', 'VX', 2024, 2026, 'sedan', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Honda', 'Amaze', 'ZX', 2024, 2026, 'sedan', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Honda', 'Elevate', 'SV', 2023, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{"Phoenix Orange Pearl","Platinum White Pearl","Obsidian Blue Pearl","Radiant Red Metallic","Lunar Silver Metallic"}'),
  ('Honda', 'Elevate', 'V', 2023, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{"Phoenix Orange Pearl","Platinum White Pearl","Obsidian Blue Pearl","Radiant Red Metallic","Lunar Silver Metallic"}'),
  ('Honda', 'Elevate', 'VX', 2023, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{"Phoenix Orange Pearl","Platinum White Pearl","Obsidian Blue Pearl","Radiant Red Metallic","Lunar Silver Metallic"}'),
  ('Honda', 'Elevate', 'ZX', 2023, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{"Phoenix Orange Pearl","Platinum White Pearl","Obsidian Blue Pearl","Radiant Red Metallic","Lunar Silver Metallic"}'),
  ('Renault', 'Kiger', 'RXE', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Renault', 'Kiger', 'RXL', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Renault', 'Kiger', 'RXT', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Renault', 'Kiger', 'RXT (O)', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Renault', 'Kiger', 'RXZ', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Renault', 'Kiger', 'RXZ Dual Tone', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Renault', 'Triber', 'Authentic', 2024, 2026, 'muv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear AC Vents","Rear Parking Sensor"}', '{}'),
  ('Renault', 'Triber', 'Evolution', 2024, 2026, 'muv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear AC Vents","Rear Parking Sensor"}', '{}'),
  ('Renault', 'Triber', 'Techno', 2024, 2026, 'muv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear AC Vents","Rear Parking Sensor"}', '{}'),
  ('Renault', 'Triber', 'Emotion', 2024, 2026, 'muv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear AC Vents","Rear Parking Sensor"}', '{}'),
  ('Renault', 'Kwid', 'RXE', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{}'),
  ('Renault', 'Kwid', 'RXL', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{}'),
  ('Renault', 'Kwid', 'RXT', 2024, 2026, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{}'),
  ('Renault', 'Kwid', 'RXZ', 2024, 2026, 'hatchback', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{}'),
  ('Nissan', 'Magnite', 'XE', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Nissan', 'Magnite', 'XL', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Nissan', 'Magnite', 'XV', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Nissan', 'Magnite', 'XV Premium', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Nissan', 'Magnite', 'XV Premium (O)', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor"}', '{}'),
  ('Škoda', 'Slavia', 'Classic', 2024, 2026, 'sedan', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{}'),
  ('Škoda', 'Slavia', 'Signature', 2024, 2026, 'sedan', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{}'),
  ('Škoda', 'Slavia', 'Prestige', 2024, 2026, 'sedan', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{}'),
  ('Škoda', 'Slavia', 'Monte Carlo', 2024, 2026, 'sedan', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{}'),
  ('Škoda', 'Kushaq', 'Classic', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{}'),
  ('Škoda', 'Kushaq', 'Signature', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{}'),
  ('Škoda', 'Kushaq', 'Prestige', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{}'),
  ('Volkswagen', 'Virtus', 'Comfortline', 2024, 2026, 'sedan', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{}'),
  ('Volkswagen', 'Virtus', 'Highline', 2024, 2026, 'sedan', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{}'),
  ('Volkswagen', 'Virtus', 'Topline', 2024, 2026, 'sedan', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{}'),
  ('Volkswagen', 'Virtus', 'GT Plus Sport', 2024, 2026, 'sedan', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{}'),
  ('Volkswagen', 'Taigun', 'Comfortline', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{}'),
  ('Volkswagen', 'Taigun', 'Highline', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{}'),
  ('Volkswagen', 'Taigun', 'GT', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{}'),
  ('Volkswagen', 'Polo', 'Trendline', 2020, 2022, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{}'),
  ('Volkswagen', 'Polo', 'Comfortline', 2020, 2022, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{}'),
  ('Volkswagen', 'Polo', 'Highline Plus', 2020, 2022, 'hatchback', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{}'),
  ('Volkswagen', 'Polo', 'GT TSI', 2020, 2022, 'hatchback', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Sensor"}', '{}'),
  ('MG Motor', 'Hector', 'Style', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","ADAS","Cruise Control"}', '{}'),
  ('MG Motor', 'Hector', 'Smart', 2024, 2026, 'suv', 'petrol', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","ADAS","Cruise Control"}', '{}'),
  ('MG Motor', 'Hector', 'Smart Pro', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","ADAS","Cruise Control"}', '{}'),
  ('MG Motor', 'Hector', 'Sharp Pro', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","ADAS","Cruise Control"}', '{}'),
  ('MG Motor', 'Hector', 'Savvy Pro', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","ADAS","Cruise Control"}', '{}'),
  ('MG Motor', 'ZS EV', 'Excite', 2024, 2026, 'suv', 'electric', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","Cruise Control"}', '{}'),
  ('MG Motor', 'ZS EV', 'Exclusive', 2024, 2026, 'suv', 'electric', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","Cruise Control"}', '{}'),
  ('MG Motor', 'ZS EV', 'Essence', 2024, 2026, 'suv', 'electric', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","Cruise Control"}', '{}'),
  ('MG Motor', 'Windsor EV', 'Excite Pro', 2024, 2026, 'muv', 'electric', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","Rear AC Vents"}', '{}'),
  ('MG Motor', 'Windsor EV', 'Exclusive Plus', 2024, 2026, 'muv', 'electric', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","Rear AC Vents"}', '{}'),
  ('BMW', '3 Series', '330i M Sport', 2024, 2026, 'sedan', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Cruise Control","Rear Parking Camera"}', '{}'),
  ('BMW', '3 Series', '330Li M Sport', 2024, 2026, 'sedan', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Cruise Control","Rear Parking Camera"}', '{}'),
  ('BMW', 'X1', 'sDrive18i M Sport', 2023, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{}'),
  ('BMW', 'X3', 'xDrive20d xLine', 2024, 2026, 'suv', 'diesel', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{}'),
  ('Mercedes-Benz', 'C-Class', 'C 200', 2022, 2026, 'sedan', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control","Rear Parking Sensor"}', '{}'),
  ('Mercedes-Benz', 'C-Class', 'C 220d', 2022, 2026, 'sedan', 'diesel', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control","Rear Parking Sensor"}', '{}'),
  ('Mercedes-Benz', 'C-Class', 'C 300d', 2022, 2026, 'sedan', 'diesel', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control","Rear Parking Sensor"}', '{}'),
  ('Mercedes-Benz', 'E-Class', 'E 200', 2024, 2026, 'sedan', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{}'),
  ('Mercedes-Benz', 'GLC', '200 4MATIC', 2023, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","Cruise Control"}', '{}'),
  ('Audi', 'A4', 'Premium', 2021, 2026, 'sedan', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{}'),
  ('Audi', 'A4', 'Premium Plus', 2021, 2026, 'sedan', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{}'),
  ('Audi', 'A4', 'Technology', 2021, 2026, 'sedan', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{}'),
  ('Audi', 'Q3', 'Premium Plus', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{}'),
  ('Audi', 'Q5', 'Technology', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{}'),
  ('Volvo', 'XC60', 'B5 Ultimate', 2022, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","ADAS","Cruise Control","Heated Seats"}', '{}'),
  ('Volvo', 'XC40', 'B4 Ultimate', 2022, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{}'),
  ('Volvo', 'XC90', 'B6 Ultimate', 2022, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","360 Camera","ADAS","Cruise Control","Heated Seats","Captain Seats"}', '{}'),
  ('Jeep', 'Compass', 'Sport', 2024, 2026, 'suv', 'diesel', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{}'),
  ('Jeep', 'Compass', 'Longitude', 2024, 2026, 'suv', 'diesel', 'manual', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{}'),
  ('Jeep', 'Compass', 'Black Shark', 2024, 2026, 'suv', 'diesel', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{}'),
  ('Jeep', 'Compass', 'Model S', 2024, 2026, 'suv', 'diesel', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Rear Parking Sensor","Cruise Control"}', '{}'),
  ('Jeep', 'Meridian', 'X', 2024, 2026, 'suv', 'diesel', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","360 Camera","Cruise Control"}', '{}'),
  ('Lexus', 'ES', '250 Exquisite', 2024, 2026, 'sedan', 'hybrid', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control","Ventilated Seats"}', '{}'),
  ('Lexus', 'ES', '250 Luxury', 2024, 2026, 'sedan', 'hybrid', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control","Ventilated Seats"}', '{}'),
  ('Lexus', 'NX', '350h', 2024, 2026, 'suv', 'hybrid', 'automatic', '{"Apple CarPlay","Android Auto","360 Camera","Cruise Control","Ventilated Seats"}', '{}'),
  ('Land Rover', 'Defender', '110 HSE', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","360 Camera","Cruise Control","Rear Parking Camera"}', '{}'),
  ('Land Rover', 'Defender', '110 X-Dynamic HSE', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","360 Camera","Cruise Control","Rear Parking Camera"}', '{}'),
  ('Land Rover', 'Defender', '130 X-Dynamic HSE', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","360 Camera","Cruise Control","Rear Parking Camera"}', '{}'),
  ('Land Rover', 'Range Rover Evoque', 'Dynamic SE', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{}'),
  ('Jaguar', 'F-Pace', 'R-Dynamic S', 2024, 2026, 'suv', 'petrol', 'automatic', '{"Apple CarPlay","Android Auto","Rear Parking Camera","Cruise Control"}', '{}'),
  ('Jaguar', 'F-Type', 'P450 R-Dynamic', 2024, 2024, 'coupe', 'petrol', 'automatic', '{"Apple CarPlay","Rear Parking Camera","Cruise Control"}', '{}')
on conflict (make, model, variant, year_start, year_end) do nothing;
